# Generated by Django 4.2.3 on 2023-07-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_question_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
